### ISSUE TITLE
Archive button required on Edit Referral screen.

### ISSUE THREAD

**Issue by snowy2651** [android-dreams/OutcomesFirst#132]
There is a requirement for an Archive button on the Edit Referral screen. This button should be enabled only if there are no live submissions (id with a status of <3). 
At the moment we wont prompt for an Archive Reason - I will check with Kerry to see if we need to add an Archive Reason of 'All Services Rejected Referral'.

**Comment by mdobson237** [comment]
There is an archive button and then archive list given - but separate bug raised as the navigation out of and saving of info are unclear in this screen
