### ISSUE TITLE
Occupancy Index Page - crashes when I hit Next Page

### ISSUE THREAD

**Issue by FulfordD** [android-dreams/OutcomesFirst#135]

**Comment by snowy2651** [comment]
Di, 
This is in progress but not assigned. Shall I assign it you or shall I move it back to High Priority & pick it up?

**Comment by snowy2651** [comment]
This has now been fixed. However, there  is an issue that we areaware of, that if any filtering is added at the top, when going to the second page, the filtering does not carry through and all records are displayed. Therefore, we are temporarily removing the Next/Previous options on the Index screens, and extending the page length, so the side bar arrow can be used to see all of the records. This will be done for All index screens until the problem can be fixed.

**Comment by mdobson237** [comment]
previous next not displayed and list of records displayed - with slide bar
