### ISSUE TITLE
Submission Index is showing submissions when the referral has been placed.

### ISSUE THREAD

**Issue by snowy2651** [android-dreams/OutcomesFirst#146]
If there are multiple submissions for one referral, the Submissions Index screen must only show the submissions if the referral has not been placed or archived. We must retain the individual statuses of the submissions for reporting purposes, so cannot archive them.

**Comment by mdobson237** [comment]
Multiple submissions for one referral 
If referral is placed the referral is no longer seen in the submissions screen
however
If referral is Archived (through edit on submission screen) the record for the service that archive happened against no longer shows in submissions screen but all other submissions for the referral still show in submissions screen.

**Comment by mdobson237** [comment]
Multiple submissions
If one archived - record is archived and others remain
If one placed all records do not appear
