### ISSUE TITLE
When Submission is placed, the placement start date must be mandatory

### ISSUE THREAD

**Issue by snowy2651** [android-dreams/OutcomesFirst#150]
When a submission is placed, the system correctly prompts for the Placement Start Date, but this is not mandatory. The system must force input of the start date.
When Submission Status is set to 'Archive', an Archive reason  must be entered

**Comment by mdobson237** [comment]
System now forces start date to be filled
However
When record set to Archive -Still problem archive reason does not have to be entered - Unless 'None' is a valid reason - Archive list shows blank entry to reason detailed on bug #143
