### ISSUE TITLE
Submissions Screen List - Displays Previous/ Next although now lists all records

### ISSUE THREAD

**Issue by mdobson237** [android-dreams/OutcomesFirst#192]
Submissions Screen
Displayed list still has previous next buttons at bottom although now displays list of all records filtered.
The previous next buttons are inactive but is this confusing for end user?

**Comment by snowy2651** [comment]
Fixed. Buttons removed as they do not work with filters.

**Comment by mdobson237** [comment]
Previous next not showing - all filtered records returned
