### ISSUE TITLE
Cannot add a submission after the referral has been created - or can you. If not, this is very high priority

### ISSUE THREAD

**Issue by FulfordD** [android-dreams/OutcomesFirst#95]

**Comment by snowy2651** [comment]
I have added this as a high priority enhancement and will work on this today

Sent from my iPhone

On 28 Aug 2019, at 08:40, FulfordD <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #95<https://github.com/android-dreams/OutcomesFirst/issues/95>.
